apiVersion: v1
kind: Service
metadata:
  name: back-end-service-prod
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 80
  selector:
    env: prod
    app: cloud-backend
    tier: backend
