- hosts: master
  become: yes
  tasks:
    - name: Necessary to do for the kubectl to work (run only once, else it will give error)
      shell:
        cmd: |
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Creating new namespace prod (run only once, else it will give error)
      command: kubectl create namespace prod

    - name: Creates directory
      file:
        path: /prod/k8s_manifest/deployments
        state: directory

    - name: copying backend file with playbook
      copy:
        src: ../k8s_manifest/prod/deployments/back_end_prod_deployment.yml
        dest: /prod/k8s_manifest/deployments/back_end_prod_deployment.yaml

    - name: Deploying backend deployment
      command: kubectl apply -f /prod/k8s_manifest/deployments/back_end_prod_deployment.yaml -n prod

    - name: copying backend file with playbook
      copy:
        src: ../k8s_manifest/prod/deployments/front_end_prod_deployment.yml
        dest: /prod/k8s_manifest/deployments/front_end_prod_deployment.yaml
  
    - name: Deploying frontend deployment
      command: kubectl apply -f /prod/k8s_manifest/deployments/front_end_prod_deployment.yaml -n prod

    - name: Creates directory
      file:
        path: /prod/k8s_manifest/services
        state: directory

    - name: copying frontend service file
      copy:
        src: ../k8s_manifest/prod/services/front_end_service_prod.yml
        dest: /prod/k8s_manifest/services/front_end_service_prod.yml 

    - name: creating service
      command: kubectl apply -f /prod/k8s_manifest/services/front_end_service_prod.yml -n prod

    - name: copying backend service file
      copy:
        src: ../k8s_manifest/prod/services/backend_service_prod.yml
        dest: /prod/k8s_manifest/services/backend_service_prod.yml 

    - name: creating service
      command: kubectl apply -f /prod/k8s_manifest/services/backend_service_prod.yml -n prod
    
